### ISSUE TITLE
New release due to vuln in dependency

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/rustfmt-wrapper#32]
https://github.com/oxidecomputer/rustfmt-wrapper/pull/31 addressed vulnerability fixed by https://github.com/Stebalien/tempfile/pull/208

Would be good to have a new release.

**Comment by jayvdb** [comment]
And there is another problem in the released crate - it depends on `toolchain_find v0.2.0`, which depends on https://crates.io/crates/pest v2.6.0 which has been yanked

**Comment by ahl** [comment]
Missed this; here you go: https://crates.io/crates/rustfmt-wrapper/0.2.1

**Comment by jayvdb** [comment]
Thanks osv-scanner now passes.
